analyze_request_task:
  description: >
    Analyze the customer's query to determine the main issue and relevant keywords about radiator issues on the document retrieval from the mail located at {pdf_path} .
  expected_output: >
    Extracted keywords about radiator issues and a summary of the customer's needs.
  agent: client_request_analysis_agent

search_document_task:
  description: >
    Search the document database for relevant documents based on the keywords and context provided by the analysis of the customer's request located at {solution_path} .
  expected_output: >
    A list of document references or sections that match the customer's issue.
  agent: document_search_agent

retrieve_document_content_task:
  description: >
    Extract specific content from the identified documents that addresses the customer's issue.
  expected_output: >
    Relevant document sections or excerpts.
  agent: document_search_agent

formulate_response_task:
  description: >
    Draft a clear and concise response for the customer, using the content extracted from the documents.
  expected_output: >
    A structured, customer-friendly response that directly addresses the query.
  agent: response_formulation_agent

quality_check_task:
  description: >
    Review the response for accuracy, relevance, and clarity to ensure it fully meets the customer's needs.
  expected_output: >
    Verified and finalized response ready for customer delivery.
  agent: quality_assurance_agent
