analyze_request_task:
  description: >
    Analyze the customer's query to determine the main issue and relevant keywords about radiator
    issues on the email.
  expected_output: >
    Extracted keywords about radiator issues and a summary of the customer's needs.
  agent: client_request_analysis_agent

filter_request_task:
  description: >
    Analyze the email located at {pdf_path} to determine if it describes an issue encountered by the 
    customer (SAV-related) or if it is unrelated. Indicate whether it is an SAV email or not.
  expected_output: >
    Return only one word: SAV or notSAV.
  agent: client_request_filter_agent

search_document_task:
  description: >
    Search the document database for relevant documents based on the keywords and context provided 
    by the analysis of the customer's request located at {solution_path} .
  expected_output: >
    A list of document references or sections that match the customer's issue from {solution_path}.
  agent: document_search_agent

retrieve_document_content_task:
  description: >
    Extract specific content from the identified documents located at {solution_path} that addresses 
    the customer's issue.
  expected_output: >
    Relevant document sections or excerpts.
  agent: document_search_agent

formulate_response_task:
  description: >
    Draft a clear and concise response for the customer, using the content extracted from the document.
  expected_output: >
    A structured, customer-friendly response that directly addresses the query.
  agent: response_formulation_agent

quality_check_task:
  description: >
    Review the response for accuracy, relevance, and clarity to ensure it fully meets the customer's needs.
  expected_output: >
    Verified and finalized response ready for customer delivery.
  agent: quality_assurance_agent

send_email_task:
  description: >
    Sends an email with the final response to the client mail based on the output 
    from the quality check task.
  expected_output: >
    A confirmation message indicating the email has been sent or failed.
  agent: email_response_agent

retrieve_client_email_task:
  description: >
    Identify and extract the client's email address from the provided email content located at {pdf_path}.
  expected_output: >
    Extracted email address of the client for further processing and communication.
  agent: email_extraction_agent

weird_expressions_task:
  description: >
    Count the proporion of weird expressions resembling to a scam in the email
  expected_output: >
    Proportion of weird expressions
  agent: text_analysis_agent

link_verification_task:
  description: >
    Checks the security of links in the email, as phishing attacks often include malicious links or dangerous files.
  expected_output: >
    Proportion of dangerous link
  agent: link_verification_agent

reporting_task:
  description: >
    Review the context you got and estimate the probability that the given document is a fraud
  expected_output: >
    A number between 0 and 1 representing the probability of fraud of the given document
  agent: fraud_probability_calculator_agent

read_task:
  description: >
    Read the content of the email located at {pdf_path} 
  expected_output: >
    Text of the mail
  agent: text_analysis_agent
