weird_expressions_task:
  description: >
    Count the proporion of weird expressions resembling to a scam
  expected_output: >
    Proportion of weird expressions
  agent: text_analysis_agent

link_verification_task:
  description: >
    Checks the security of links in the email, as phishing attacks often include malicious links or dangerous files.
  expected_output: >
    Proportion of dangerous link
  agent: link_verification_agent

reporting_task:
  description: >
    Review the context you got and estimate the probability that the given document is a fraud
  expected_output: >
    A number between 0 and 1 representing the probability of fraud of the given document
  agent: fraud_probability_calculator_agent

read_task:
  description: >
    Read the content of the mail located at {pdf_path} 
  expected_output: >
    Text of the mail
  agent: text_analysis_agent
